name: import terraform

on: workflow_dispatch

jobs:
  import_terraform:
    name: Import Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id                = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region                    = "${{ secrets.GCP_REGION }}"
          gke_cluster_name              = "${{ secrets.GKE_CLUSTER_NAME }}"
          gke_location                  = "${{ secrets.GKE_LOCATION }}"
          gke_pool_name                 = "${{ secrets.GKE_POOL_NAME }}"
          gke_node_preemptible          = "${{ secrets.GKE_NODE_PREEMPTIBLE }}"
          gke_node_machine_type         = "${{ secrets.GKE_NODE_MACHINE_TYPE }}"
          gcr_image_name                = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/naka:${{ needs.publish_image.outputs.img_tag }}"
          gke_deployment_name           = "${{ secrets.GKE_DEPLOYMENT_NAME }}"
          naka_kai_discord_token        = "${{ secrets.NAKA_DISCORD_TOKEN }}"
          naka_kai_discord_delete_time  = "${{ secrets.NAKA_KAI_DISCORD_DELETE_TIME }}"
          naka_kai_discord_queue_limit  = "${{ secrets.NAKA_KAI_DISCORD_QUEUE_LIMIT }}"
          naka_kai_db_dialect           = "${{ secrets.NAKA_KAI_DB_DIALECT }}"
          naka_kai_db_address           = "${{ secrets.NAKA_KAI_DB_ADDRESS }}"
          naka_kai_db_name              = "${{ secrets.NAKA_KAI_DB_NAME }}"
          naka_kai_db_user              = "${{ secrets.NAKA_KAI_DB_USER }}"
          naka_kai_db_password          = "${{ secrets.NAKA_KAI_DB_PASSWORD }}"
          naka_kai_youtube_key          = "${{ secrets.NAKA_YOUTUBE_KEY }}"
          naka_kai_log_level            = "${{ secrets.NAKA_LOG_LEVEL }}"
          naka_kai_log_json             = "${{ secrets.NAKA_LOG_JSON }}"
          naka_kai_newrelic_license_key = "${{ secrets.NAKA_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Import Terraform
        run: |
          terraform import -input=false google_container_cluster.cluster ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}
          terraform import -input=false google_container_node_pool.pool ${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GKE_LOCATION }}/${{ secrets.GKE_CLUSTER_NAME }}/${{ secrets.GKE_POOL_NAME }}
          terraform import -input=false kubernetes_deployment.bot default/${{ secrets.GKE_DEPLOYMENT_NAME }}
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}