name: publish & deploy

on:
  push:
    tags:
      - "v*"

jobs:
  publish_image:
    name: Build and push naka-kai image
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.tag.outputs.img_tag }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
      - name: Remove 'v' from tag
        id: tag
        env:
          github_ref: ${{ github.ref }}
        run: |
          github_ref=${github_ref##*/}
          github_ref=${github_ref/v/}
          echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
          echo "img_tag=${github_ref}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Setup docker
        run: |
          gcloud --quiet auth configure-docker
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: |
            rl404/naka-kai:latest
            rl404/naka-kai:${{ env.IMG_TAG }}
            ghcr.io/rl404/naka-kai:latest
            ghcr.io/rl404/naka-kai:${{ env.IMG_TAG }}
            ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/naka-kai:${{ env.IMG_TAG }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - uses: actions/checkout@v5
      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id                = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region                    = "${{ secrets.GCP_REGION }}"
          gke_cluster_name              = "${{ secrets.GKE_CLUSTER_NAME }}"
          gke_location                  = "${{ secrets.GKE_LOCATION }}"
          gke_pool_name                 = "${{ secrets.GKE_POOL_NAME }}"
          gke_node_preemptible          = "${{ secrets.GKE_NODE_PREEMPTIBLE }}"
          gke_node_machine_type         = "${{ secrets.GKE_NODE_MACHINE_TYPE }}"
          gke_node_disk_size_gb         = "${{ secrets.GKE_NODE_DISK_SIZE_GB }}"
          gcr_image_name                = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/naka-kai:${{ needs.publish_image.outputs.img_tag }}"
          gke_deployment_name           = "${{ secrets.GKE_DEPLOYMENT_NAME }}"
          naka_kai_discord_token        = "${{ secrets.NAKA_KAI_DISCORD_TOKEN }}"
          naka_kai_discord_delete_time  = "${{ secrets.NAKA_KAI_DISCORD_DELETE_TIME }}"
          naka_kai_discord_queue_limit  = "${{ secrets.NAKA_KAI_DISCORD_QUEUE_LIMIT }}"
          naka_kai_db_dialect           = "${{ secrets.NAKA_KAI_DB_DIALECT }}"
          naka_kai_db_address           = "${{ secrets.NAKA_KAI_DB_ADDRESS }}"
          naka_kai_db_name              = "${{ secrets.NAKA_KAI_DB_NAME }}"
          naka_kai_db_user              = "${{ secrets.NAKA_KAI_DB_USER }}"
          naka_kai_db_password          = "${{ secrets.NAKA_KAI_DB_PASSWORD }}"
          naka_kai_youtube_key          = "${{ secrets.NAKA_YOUTUBE_KEY }}"
          naka_kai_log_level            = "${{ secrets.NAKA_KAI_LOG_LEVEL }}"
          naka_kai_log_json             = "${{ secrets.NAKA_KAI_LOG_JSON }}"
          naka_kai_newrelic_license_key = "${{ secrets.NAKA_KAI_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Format Terraform
        run: terraform fmt -check
      - name: Plan Terraform
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Apply Terraform
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
